FROM archlinux:rolling

LABEL "com.github.actions.name"="Bienvenu en ligne."
LABEL "com.github.actions.description"="Démarrage de 'ArchLinux:Rolling' dans un conteneur Docker."
LABEL "com.github.actions.stdout="echo The standard output."
LABEL "com.github.actions.icon"="oci"
LABEL "com.github.actions.color"="blue"

LABEL "repository"="http://github.com/acidburn0zzz/hello-github-actions"
LABEL "homepage"="http://github.com/acidburn0zzz"
LABEL "maintainer"="Acidburn0zzz <acidbinside@vivaldi.net>"

ADD bash /usr/bin/bash
ENTRYPOINT ["/usr/bin/bash"]
